### ISSUE TITLE
Request not in the context of DRYPermissionsField

### ISSUE THREAD

**Issue by GerardPaligot** [Helioscene/dry-rest-permissions#16]
When I specify `DRYPermissionsField` in my serializer used for my view to create a new profile, I got an exception from dry-rest-permissions which said me that I don't have a `request` in my context field:

```console
Error
Traceback (most recent call last):
  File "/Users/gerard/Documents/workspace-django/zds-site/zds/member/api/tests.py", line 166, in test_register_two_same_users
    response = self.client.post(reverse('api-member-list'), data)
  File "/Users/gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/rest_framework/test.py", line 168, in post
    path, data=data, format=format, content_type=content_type, **extra)
  File "/Users/gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/rest_framework/test.py", line 90, in post
    return self.generic('POST', path, data, content_type, **extra)
  File "/Users/gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/rest_framework/compat.py", line 222, in generic
    return self.request(**r)
  File "/Users/gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/rest_framework/test.py", line 157, in request
    return super(APIClient, self).request(**kwargs)
  File "/Users/gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/rest_framework/test.py", line 109, in request
    request = super(APIRequestFactory, self).request(**kwargs)
  File "/Users/gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/django/test/client.py", line 440, in request
    six.reraise(*exc_info)
  File "/Users/gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/rest_framework/views.py", line 452, in dispatch
    response = self.handle_exception(exc)
  File "/Users/gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/rest_framework/views.py", line 449, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/gerard/Documents/workspace-django/zds-site/zds/member/api/views.py", line 95, in post
    headers = self.get_success_headers(serializer.data)
  File "/Users/gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/rest_framework/serializers.py", line 466, in data
    ret = super(Serializer, self).data
  File "/Users/gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/rest_framework/serializers.py", line 213, in data
    self._data = self.to_representation(self.instance)
  File "/Users/gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/rest_framework/serializers.py", line 435, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/Users/gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/dry_rest_permissions/generics.py", line 261, in to_representation
    results[action] = getattr(self.parent.Meta.model, method_names['global'])(self.context['request'])
KeyError: 'request'
```

My test case is below and failed at the first post request:

```python
def test_register_two_same_users(self):
    """
    Tries to register a user two times.
    """
    data = {
        'username': 'Clem',
        'email': 'clem@zestedesavoir.com',
        'password': 'azerty'
    }
    response = self.client.post(reverse('api-member-list'), data)
    self.assertEqual(response.status_code, status.HTTP_201_CREATED)

    response = self.client.post(reverse('api-member-list'), data)
    self.assertEqual(response.status_code, status.HTTP_400_BAD_REQUEST)
    self.assertIsNotNone(response.data.get('username'))
    self.assertIsNotNone(response.data.get('email'))
```

I use this serializer:

```python
class ProfileCreateSerializer(serializers.ModelSerializer, ProfileCreate, ProfileUsernameValidator,
                              ProfileEmailValidator):
    """
    Serializers of a user object to create one.
    """

    id = serializers.ReadOnlyField(source='user.id')
    username = serializers.CharField(source='user.username')
    email = serializers.EmailField(source='user.email')
    password = serializers.CharField(source='user.password')
    permissions = DRYPermissionsField(additional_actions=['ban'])

    class Meta:
        model = Profile
        fields = ('id', 'username', 'email', 'password', 'permissions')
        write_only_fields = ('password')

    def create(self, validated_data):
        # Some logic to create a new profile.
        return profile

    def throw_error(self, key=None, message=None):
        raise serializers.ValidationError(message)
```

Any ideas?

**Comment by GerardPaligot** [comment]
For information, at the statement which throws an exception. This part `getattr(self.parent.Meta.model, method_names['global'])` works and returns the correct function in my model but this other part `self.context['request']` doesn't work.

And I suspect that the request can be null because the `FileField` class in Django have this implementation of `to_representation`:

```python
class FileField(Field):
    default_error_messages = {
        'required': _('No file was submitted.'),
        'invalid': _('The submitted data was not a file. Check the encoding type on the form.'),
        'no_name': _('No filename could be determined.'),
        'empty': _('The submitted file is empty.'),
        'max_length': _('Ensure this filename has at most {max_length} characters (it has {length}).'),
    }
    use_url = api_settings.UPLOADED_FILES_USE_URL

    def __init__(self, *args, **kwargs):
        self.max_length = kwargs.pop('max_length', None)
        self.allow_empty_file = kwargs.pop('allow_empty_file', False)
        self.use_url = kwargs.pop('use_url', self.use_url)
        super(FileField, self).__init__(*args, **kwargs)

    # methods ...

    def to_representation(self, value):
        if self.use_url:
            if not value:
                return None
            url = value.url
            request = self.context.get('request', None)
            if request is not None:
                return request.build_absolute_uri(url)
            return url
        return value.name
```

**Comment by GerardPaligot** [comment]
Ok, I fixed this issue with this:

```python
ProfileCreateSerializer(data=request.data, context={'request': request})
```

Maybe that could be a good idea to improve the code to inform the developer of this usage?

**Comment by dbkaplan** [comment]
Added to documentation
