### ISSUE TITLE
dry-rest-permissions doesn't support generic view

### ISSUE THREAD

**Issue by GerardPaligot** [Helioscene/dry-rest-permissions#17]
When I have a generic view like this one:

```python
class MemberDetailAPI(RetrieveUpdateAPIView):
    """
    Profile resource to display or update details of a member.
    """

    queryset = Profile.objects.all()
    lookup_field = 'user__id'
    obj_key_func = DetailKeyConstructor()
    permission_classes = (DRYPermissions,)

    @etag(obj_key_func)
    @cache_response(key_func=obj_key_func)
    def get(self, request, *args, **kwargs):
        profile = self.get_object()
        serializer = self.get_serializer(profile,
                                         show_email=profile.show_email,
                                         is_authenticated=self.request.user.is_authenticated())
        return Response(serializer.data)

    @etag(obj_key_func, rebuild_after_method_evaluation=True)
    def put(self, request, *args, **kwargs):
        self.permission_classes = (IsAuthenticatedOrReadOnly, IsOwnerOrReadOnly)
        return self.update(request, *args, **kwargs)

    def get_serializer_class(self):
        if self.request.method == 'GET':
            return ProfileDetailSerializer
        elif self.request.method == 'PUT':
            return ProfileValidatorSerializer
```

and make a DELETE request, I should have a HTTP code 405 METHOD_NOT_ALLOWED but dry-rest-permissions throws an exception first due to [this line](https://github.com/Helioscene/dry-rest-permissions/blob/master/dry_rest_permissions/generics.py#L106). How you can see in my view, I don't have a serializer for DELETE method. `serializer_class` is None and throws this exception:

```console
Error
Traceback (most recent call last):
  File "/Users/gerard/Documents/workspace-django/zds-site/zds/member/api/tests.py", line 654, in test_member_detail_url_with_delete_method
    response = self.client.delete(reverse('api-member-detail', args=[self.profile.user.id]))
  File "/Users/gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/rest_framework/test.py", line 192, in delete
    path, data=data, format=format, content_type=content_type, **extra)
  File "/Users/gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/rest_framework/test.py", line 102, in delete
    return self.generic('DELETE', path, data, content_type, **extra)
  File "/Users/gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/rest_framework/compat.py", line 222, in generic
    return self.request(**r)
  File "/Users/gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/rest_framework/test.py", line 157, in request
    return super(APIClient, self).request(**kwargs)
  File "/Users/gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/rest_framework/test.py", line 109, in request
    request = super(APIRequestFactory, self).request(**kwargs)
  File "/Users/gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/django/test/client.py", line 440, in request
    six.reraise(*exc_info)
  File "/Users/gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/rest_framework/views.py", line 452, in dispatch
    response = self.handle_exception(exc)
  File "/Users/gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/rest_framework/views.py", line 440, in dispatch
    self.initial(request, *args, **kwargs)
  File "/Users/gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/rest_framework/views.py", line 355, in initial
    self.check_permissions(request)
  File "/Users/gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/rest_framework/views.py", line 300, in check_permissions
    if not permission.has_permission(request, self):
  File "/Users/gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/dry_rest_permissions/generics.py", line 106, in has_permission
    assert serializer_class.Meta.model is not None, (
AttributeError: 'NoneType' object has no attribute 'Meta'
```

**Comment by GerardPaligot** [comment]
I fixe this issue with this usage in my view:

```python
    def get_permissions(self):
        if self.request.method == 'GET' or self.request.method == 'PUT':
            return [DRYPermissions,]
        return []
```

I don't know if it is the better way to solve this problem but if yes, that could be a good idea to integrate it in your documentation for generic views.

**Comment by dbkaplan** [comment]
Added to documentation
